
FIND_PATH(SHA_INCLUDE_DIR openssl/sha.h
/usr/include/
/usr/local/include/
${GNUWIN32_INSTALL_PREFIX}/include
)

FIND_LIBRARY(SHA_LIBRARIES NAMES crypto
PATHS
/usr/lib/
/usr/local/lib/
${GNUWIN32_INSTALL_PREFIX}/lib
)

IF(SHA_INCLUDE_DIR AND SHA_LIBRARIES)
   SET(SHA_FOUND TRUE)
ENDIF(SHA_INCLUDE_DIR AND SHA_LIBRARIES)


IF(SHA_FOUND)
   IF(NOT OpenSSL_FIND_QUIETLY)
      MESSAGE(STATUS "Found Sha: ${SHA_LIBRARIES}")
   ENDIF(NOT OpenSSL_FIND_QUIETLY)
ELSE(SHA_FOUND)
   IF(Sha_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Sha. Please install libssl-dev")
   ENDIF(Sha_FIND_REQUIRED)
ENDIF(SHA_FOUND)

MARK_AS_ADVANCED(
  SHA_INCLUDE_DIR
  SHA_LIBRARIES
)
